name: Clean Architecture CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    uses: codekoller/workflow-templates/.github/workflows/codekoller-ci.yml@main
